const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.resolve(__dirname, '../assets');
const badgesDirName = fs.readdirSync(ASSETS_DIR).find(
  (d) => d.toLowerCase() === 'badges' && fs.statSync(path.join(ASSETS_DIR, d)).isDirectory(),
) ?? 'badges';
const BADGES_ASSET_DIR = path.join(ASSETS_DIR, badgesDirName);
const OUTPUT_FILE = path.resolve(__dirname, '../src/data/badges/badgeImages.ts');

const files = fs.existsSync(BADGES_ASSET_DIR)
  ? fs.readdirSync(BADGES_ASSET_DIR).filter((f) => /^badge_[a-z0-9_]+\.png$/.test(f))
  : [];

const entries = files.map((filename) => {
  const id = filename.replace(/^badge_/, '').replace(/\.png$/, '');
  return `  ${id}: require('../../../assets/${badgesDirName}/${filename}'),`;
});

const content = `// AUTO-GENERATED by scripts/generateBadgeImages.js — do not edit manually
// Add a PNG to assets/${badgesDirName}/ named badge_<id>.png, then run: npm run codegen:badge-images
import { ImageSourcePropType } from 'react-native';

export const BADGE_IMAGES: Record<string, ImageSourcePropType> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
console.log(`✓ badgeImages.ts generated (${entries.length} images)`);
