import fs from 'fs';
import path from 'path';

const BADGES_ASSET_DIR = path.resolve(__dirname, '../assets/badges');
const OUTPUT_FILE = path.resolve(__dirname, '../src/data/badges/badgeImages.ts');

const files = fs.existsSync(BADGES_ASSET_DIR)
  ? fs.readdirSync(BADGES_ASSET_DIR).filter((f) => /^badge_[a-z0-9_]+\.png$/.test(f))
  : [];

const entries = files.map((filename) => {
  const id = filename.replace(/^badge_/, '').replace(/\.png$/, '');
  return `  ${id}: require('../../../assets/badges/${filename}'),`;
});

const content = `// AUTO-GENERATED by scripts/generateBadgeImages.ts — do not edit manually
// Add a PNG to assets/badges/ named badge_<id>.png and re-run \`npm start\`
import { ImageSourcePropType } from 'react-native';

export const BADGE_IMAGES: Record<string, ImageSourcePropType> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
console.log(`✓ badgeImages.ts generated (${entries.length} images)`);
