// AUTO-GENERATED by scripts/generateBadgeImages.js — do not edit manually
// Add a PNG to assets/Badges/ named badge_<id>.png, then run: npm run codegen:badge-images
import { ImageSourcePropType } from 'react-native';

export const BADGE_IMAGES: Record<string, ImageSourcePropType> = {
  creative_spark: require('../../../assets/Badges/badge_creative_spark.png'),
  first_quest: require('../../../assets/Badges/badge_first_quest.png'),
  fresh_air: require('../../../assets/Badges/badge_fresh_air.png'),
  home_reset: require('../../../assets/Badges/badge_home_reset.png'),
  quest_collector: require('../../../assets/Badges/badge_quest_collector.png'),
  real_life_adventurer: require('../../../assets/Badges/badge_real_life_adventurer.png'),
  seven_day_streak: require('../../../assets/Badges/badge_seven_day_streak.png'),
  social_starter: require('../../../assets/Badges/badge_social_starter.png'),
  three_day_streak: require('../../../assets/Badges/badge_three_day_streak.png'),
};
