// AUTO-GENERATED by scripts/generateBadgeImages.ts — do not edit manually
// Add a PNG to assets/badges/ named badge_<id>.png and re-run `npm start`
import { ImageSourcePropType } from 'react-native';

export const BADGE_IMAGES: Record<string, ImageSourcePropType> = {
  creative_spark: require('../../../assets/badges/badge_creative_spark.png'),
  fresh_air: require('../../../assets/badges/badge_fresh_air.png'),
  home_reset: require('../../../assets/badges/badge_home_reset.png'),
  quest_collector: require('../../../assets/badges/badge_quest_collector.png'),
  real_life_adventurer: require('../../../assets/badges/badge_real_life_adventurer.png'),
  seven_day_streak: require('../../../assets/badges/badge_seven_day_streak.png'),
  social_starter: require('../../../assets/badges/badge_social_starter.png'),
  three_day_streak: require('../../../assets/badges/badge_three_day_streak.png'),
};
